# for *-php-fpm and *-hhvm base image
app:
    build: ./
    volumes:
        - ./:/var/www/html/
    links:
        - db:db
    environment:
        ENABLE_ENV_FILE: 1
        API_TOKEN: "<YOUR GITHUB API TOKEN>"

nginx:
    build: ./nginx
    ports:
        - "8080:80"
    links:
        - app
    volumes_from:
        - app

db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret-root
        MYSQL_DATABASE: web
        MYSQL_USER: web
        MYSQL_PASSWORD: web
