<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Assignments have been updated',
    'Auth item with such name already exists' => 'Auth item with such name already exists',
    'Class "{0}" does not exist' => 'Class "{0}" does not exists',
    'Classname of the rule associated with this item' => 'Classname of the rule associate with this item',
    'Create' => '创建',
    'Create new permission' => '创建新权限',
    'Create new role' => '创建新角色',
    'Description' => '描述',
    'Invalid value' => 'Invalid value',
    'Item has been created' => 'Item has been created',
    'Item has been updated' => 'Item has been updated',
    'Name' => '名称',
    'New permission' => '新权限',
    'New role' => '新角色',
    'New user' => '新用户',
    'Permissions' => '权限',
    'Roles' => '角色',
    'Rule class can not be instantiated' => 'Rule class can not be instantiated',
    'Rule class must extend "yii\rbac\Rule"' => 'Rule class must extend "yii\rbac\Rule"',
    'Rule name' => 'Rule name',
    'Save' => '保存',
    'The item description (Optional).' => 'The item description (Optional).',
    'The name of the item.' => 'The name of the Item',
    'There is neither role nor permission with name "{0}"' => 'There is neither role nor permission with name"{0}"',
    'Update assignments' => '更新任务',
    'Update permission' => '更新权限',
    'Update role' => '更新角色',
    'Users' => '用户',
];
